apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
