apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-db-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: db
    managed-by: Helm
spec:
  {{- if .Values.db.replica_count }}
  replicas: {{ .Values.db.replica_count }}
  {{- end }}
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: {{ .Chart.Name }}
        image: {{ .Values.db.image }}
        ports:
        - containerPort: {{ .Values.db.containerPort }}
