apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-db-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.db.service.type | default "ClusterIP" }}
  selector:
    app: db
  ports:
    - name: "{{ .Values.db.service.targetPort }}"
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
